# Generated by Django 4.0.2 on 2023-03-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='profile_pic',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.post'),
        ),
    ]
