# Generated by Django 4.0.2 on 2023-03-17 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_profile_pic_files_pic_alter_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.post'),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
