# Generated by Django 4.0.2 on 2023-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_files_post_alter_files_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='pic',
            new_name='profile_pic',
        ),
    ]
