# Generated by Django 4.0.2 on 2023-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_post_dislike_post_like_liked_disliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='disliked',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liked',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
